export { default as AnalyticsBlock } from './Analytics'
export { default as NewsBlock } from './NFT'
export { default as NFTBlock } from './NFT.Storage'
export { default as NFT_Storage } from './News'
export { default as Wallet } from './Wallet'
